using PinqOps.Proxy;
using Xunit;

namespace PinqOps.Tests.Proxy;

public class CaddyfileGeneratorTests
{
    private static DomainEntry Entry(string domain, string container, int port, bool enabled = true) =>
        new() { Domain = domain, TargetContainer = container, TargetPort = port, Enabled = enabled };

    [Fact]
    public void EmptyConfig_HasOnlyTheHeader()
    {
        var caddyfile = CaddyfileGenerator.Generate(new DomainConfig());

        Assert.Equal("# Generated by pinqops-ui — do not edit; changes are overwritten.\n", caddyfile);
    }

    [Fact]
    public void SingleDomain_RendersASiteBlock()
    {
        var config = new DomainConfig
        {
            AcmeEmail = "ops@example.com",
            Domains = [Entry("app.example.com", "myrepo-app-1", 3000)],
        };

        var caddyfile = CaddyfileGenerator.Generate(config);

        Assert.Contains("email ops@example.com", caddyfile);
        Assert.Contains("app.example.com {\n    reverse_proxy myrepo-app-1:3000\n}\n", caddyfile);
        Assert.DoesNotContain("acme_ca", caddyfile);
    }

    [Fact]
    public void StagingCa_EmitsTheStagingDirective()
    {
        var config = new DomainConfig { UseStagingCa = true, Domains = [Entry("a.example.com", "c", 80)] };

        Assert.Contains("acme_ca https://acme-staging-v02.api.letsencrypt.org/directory", CaddyfileGenerator.Generate(config));
    }

    [Fact]
    public void DisabledOrUnresolvedEntries_AreSkipped()
    {
        var config = new DomainConfig
        {
            Domains =
            [
                Entry("off.example.com", "c1", 80, enabled: false),
                Entry("noport.example.com", "c2", 0),
                Entry("live.example.com", "c3", 8080),
            ],
        };

        var caddyfile = CaddyfileGenerator.Generate(config);

        Assert.DoesNotContain("off.example.com", caddyfile);
        Assert.DoesNotContain("noport.example.com", caddyfile);
        Assert.Contains("live.example.com {", caddyfile);
    }

    [Fact]
    public void NoEmail_OmitsTheGlobalBlock()
    {
        var config = new DomainConfig { Domains = [Entry("a.example.com", "c", 80)] };

        Assert.DoesNotContain("{\n    email", CaddyfileGenerator.Generate(config));
    }
}

public class DomainNameTests
{
    [Theory]
    [InlineData("App.Example.COM", "app.example.com")]
    [InlineData("api.example.com.", "api.example.com")]
    public void Normalize_LowercasesAndTrims(string input, string expected)
    {
        Assert.Equal(expected, DomainName.Normalize(input));
    }

    [Theory]
    [InlineData("")]
    [InlineData("*.example.com")]
    [InlineData("not a domain")]
    [InlineData("http://example.com")]
    public void Normalize_RejectsInvalid(string input)
    {
        Assert.Throws<ArgumentException>(() => DomainName.Normalize(input));
    }
}

public class DomainConfigStoreTests : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("pinqops-domains-").FullName;

    public void Dispose() => Directory.Delete(_dir, recursive: true);

    [Fact]
    public void SaveThenLoad_RoundTrips()
    {
        var store = new DomainConfigStore(_dir);
        var config = new DomainConfig
        {
            AcmeEmail = "ops@example.com",
            Domains = [new DomainEntry { Domain = "a.example.com", Target = "acme-shop", TargetContainer = "acme-shop-app-1", TargetPort = 3000 }],
        };

        store.Save(config);
        var loaded = new DomainConfigStore(_dir).Load();

        Assert.Equal("ops@example.com", loaded.AcmeEmail);
        var entry = Assert.Single(loaded.Domains);
        Assert.Equal("a.example.com", entry.Domain);
        Assert.Equal("acme-shop-app-1", entry.TargetContainer);
    }

    [Fact]
    public void Load_CorruptFile_ReturnsEmpty()
    {
        File.WriteAllText(ProxyPaths.DomainsFile(_dir), "{ not json");

        Assert.Empty(new DomainConfigStore(_dir).Load().Domains);
    }
}
