namespace PinqOps;

/// <summary>
/// The application compose project pinqops generates — shared by the dashboard
/// (the fixed prod project) and the CLI (per-PR preview projects), so both emit
/// exactly the same shape. The project name is explicit so a preview can use
/// <c>&lt;repo&gt;-pr-&lt;n&gt;</c> instead of the repository name.
/// </summary>
public static class ComposeTemplate
{
    public static string Yaml(string owner, string repo, string projectName, int hostPort, int containerPort) =>
        $$"""
        # Generated by pinqops-ui — the application compose project.
        # `pinqops deploy` runs: docker compose pull && docker compose up -d
        # Quoted: an all-digit project name (e.g. "2048") would otherwise be
        # read as a YAML integer and compose rejects the file outright.
        name: "{{projectName}}"

        services:
          app:
            # Both variables are pinned in this directory's .env by `pinqops
            # deploy` (PINQOPS_IMAGE from --image, PINQOPS_TAG from --tag), so the
            # image always follows the repository — even after a rename — and the
            # exact version is recorded and can be rolled back. The defaults below
            # are used only before the first deploy (or a plain `docker compose up`).
            image: ${PINQOPS_IMAGE:-ghcr.io/{{owner.ToLowerInvariant()}}/{{repo.ToLowerInvariant()}}}:${PINQOPS_TAG:-latest}
            restart: unless-stopped
            # <host>:<container>. Change the host port from the dashboard's .env
            # editor (PINQOPS_HOST_PORT) and press Apply — no need to edit YAML.
            # PINQOPS_CONTAINER_PORT is the port your image listens on; it was
            # read from your Dockerfile's EXPOSE.
            ports:
              - "${PINQOPS_HOST_PORT:-{{hostPort}}}:${PINQOPS_CONTAINER_PORT:-{{containerPort}}}"
            # pinqops-apps is the shared network the catalog apps live on — it
            # lets this app reach them (Redis, PostgreSQL, …) by container DNS.
            networks: [default, pinqops-apps]
            # Add whatever else YOUR application needs here (volumes, env):

        networks:
          pinqops-apps:
            external: true
        """;
}
