using System.Globalization;

namespace PinqOps;

/// <summary>
/// Generates a starting Dockerfile for a detected <see cref="StackResult"/>. Every
/// template declares a single runtime-stage <c>EXPOSE</c> equal to
/// <see cref="StackResult.SuggestedPort"/>, so the existing
/// <see cref="DockerfileInspector"/> reads the same port back and the publish
/// flow is unchanged. The output is a starting point the user reviews and edits.
/// </summary>
public static class DockerfileTemplates
{
    public static string For(StackResult result)
    {
        var port = result.SuggestedPort.ToString(CultureInfo.InvariantCulture);
        var hints = result.BuildHints;
        return result.Kind switch
        {
            StackKind.Node => Node(port, hints),
            StackKind.DotNet => DotNet(port, hints),
            StackKind.Go => Go(port),
            StackKind.Rust => Rust(port, hints),
            StackKind.Python => Python(port, hints),
            StackKind.Php => Php(port, hints),
            StackKind.Ruby => Ruby(port, hints),
            StackKind.Static => Static(port),
            _ => Unknown(port),
        };
    }

    private static string Node(string port, IReadOnlyDictionary<string, string> hints)
    {
        var version = hints.TryGetValue("nodeVersion", out var v) ? v : "22";
        return $"""
            # Generated by pinqops — a starting point; review and edit for your app.
            FROM node:{version}-alpine AS build
            WORKDIR /app
            COPY package*.json ./
            RUN npm ci
            COPY . .
            RUN npm run build --if-present

            FROM node:{version}-alpine
            WORKDIR /app
            ENV NODE_ENV=production
            COPY --from=build /app ./
            EXPOSE {port}
            CMD ["npm", "start"]
            """;
    }

    private static string DotNet(string port, IReadOnlyDictionary<string, string> hints)
    {
        var sdk = hints.TryGetValue("targetFramework", out var tfm) ? SdkVersion(tfm) : "9.0";
        var project = hints.TryGetValue("csprojName", out var csproj) ? csproj : ".";
        var dll = hints.TryGetValue("dllName", out var d) ? d : "App.dll";
        return $"""
            # Generated by pinqops — a starting point; review and edit for your app.
            FROM mcr.microsoft.com/dotnet/sdk:{sdk} AS build
            WORKDIR /src
            COPY . .
            RUN dotnet restore
            RUN dotnet publish {project} -c Release -o /app --no-restore

            FROM mcr.microsoft.com/dotnet/aspnet:{sdk}
            WORKDIR /app
            COPY --from=build /app ./
            ENV ASPNETCORE_URLS=http://+:{port}
            EXPOSE {port}
            ENTRYPOINT ["dotnet", "{dll}"]
            """;
    }

    private static string Go(string port) =>
        $"""
        # Generated by pinqops — a starting point; review and edit for your app.
        FROM golang:1-alpine AS build
        WORKDIR /src
        COPY go.* ./
        RUN go mod download
        COPY . .
        RUN CGO_ENABLED=0 go build -o /server .

        FROM alpine:latest
        RUN apk add --no-cache ca-certificates
        COPY --from=build /server /server
        EXPOSE {port}
        ENTRYPOINT ["/server"]
        """;

    private static string Rust(string port, IReadOnlyDictionary<string, string> hints)
    {
        var bin = hints.TryGetValue("binName", out var b) ? b : "app";
        return $"""
            # Generated by pinqops — a starting point; review and edit for your app.
            FROM rust:1-slim AS build
            WORKDIR /src
            COPY . .
            RUN cargo build --release

            FROM debian:bookworm-slim
            RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
            COPY --from=build /src/target/release/{bin} /usr/local/bin/app
            EXPOSE {port}
            ENTRYPOINT ["/usr/local/bin/app"]
            """;
    }

    private static string Python(string port, IReadOnlyDictionary<string, string> hints)
    {
        var framework = hints.TryGetValue("framework", out var f) ? f : "";
        var cmd = framework switch
        {
            "fastapi" or "uvicorn" =>
                $"""CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "{port}"]""",
            "django" =>
                $"""
                # Adjust "yourproject.wsgi" to your project's WSGI module.
                CMD ["gunicorn", "--bind", "0.0.0.0:{port}", "yourproject.wsgi"]
                """,
            "flask" =>
                $"""CMD ["gunicorn", "--bind", "0.0.0.0:{port}", "app:app"]""",
            _ =>
                """
                # Set the command that starts your app, e.g.:
                CMD ["python", "app.py"]
                """,
        };
        return $"""
            # Generated by pinqops — a starting point; review and edit for your app.
            FROM python:3.12-slim
            WORKDIR /app
            COPY requirements.txt* pyproject.toml* ./
            RUN pip install --no-cache-dir -r requirements.txt
            COPY . .
            EXPOSE {port}
            {cmd}
            """;
    }

    private static string Php(string port, IReadOnlyDictionary<string, string> hints)
    {
        var laravel = hints.TryGetValue("framework", out var f) && f == "laravel";
        var docroot = laravel
            ? "\n# Laravel serves from /public:\nENV APACHE_DOCUMENT_ROOT=/var/www/html/public\nRUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf /etc/apache2/apache2.conf"
            : "";
        return $"""
            # Generated by pinqops — a starting point; review and edit for your app.
            FROM php:8.3-apache
            RUN a2enmod rewrite
            WORKDIR /var/www/html
            COPY . .{docroot}
            EXPOSE {port}
            """;
    }

    private static string Ruby(string port, IReadOnlyDictionary<string, string> hints)
    {
        var rails = hints.TryGetValue("framework", out var f) && f == "rails";
        var cmd = rails
            ? $"""CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "{port}"]"""
            : """
              # Set the command that starts your app, e.g.:
              CMD ["ruby", "app.rb"]
              """;
        return $"""
            # Generated by pinqops — a starting point; review and edit for your app.
            FROM ruby:3.3-slim
            WORKDIR /app
            RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
            COPY Gemfile* ./
            RUN bundle install
            COPY . .
            EXPOSE {port}
            {cmd}
            """;
    }

    private static string Static(string port) =>
        $"""
        # Generated by pinqops — a starting point; review and edit for your app.
        FROM nginx:alpine
        COPY . /usr/share/nginx/html
        EXPOSE {port}
        """;

    private static string Unknown(string port) =>
        $"""
        # pinqops could not detect your stack — fill in the build below.
        # Replace the base image, build step, and start command for your app.
        FROM alpine:latest
        WORKDIR /app
        COPY . .
        # RUN <build your app>
        EXPOSE {port}
        # CMD ["<start your app>"]
        """;

    /// <summary>".NET SDK/runtime image tag from a target framework: net9.0 → 9.0.</summary>
    private static string SdkVersion(string targetFramework)
    {
        var match = System.Text.RegularExpressions.Regex.Match(targetFramework, @"net(\d+\.\d+)");
        return match.Success ? match.Groups[1].Value : "9.0";
    }
}
