namespace PinqOps.Web;

/// <summary>
/// File templates the dashboard can materialize for a repository that is
/// missing them — the deploy workflow (committed to the repo via the GitHub
/// API) and the fixed server-side compose project.
/// </summary>
public static class SetupTemplates
{
    /// <summary>Mirror of examples/workflows/deploy.yml, ready to commit.</summary>
    public const string DeployWorkflowYaml =
        """
        # Generated by pinqops-ui. Build in the cloud, deploy over the
        # self-hosted runner's outbound link — no inbound port on the server.

        name: Build and Deploy

        on:
          push:
            branches:
              - master

        permissions:
          contents: read

        concurrency:
          group: deploy-master
          cancel-in-progress: true

        jobs:
          build:
            runs-on: ubuntu-latest
            permissions:
              contents: read
              packages: write
            env:
              IMAGE: ghcr.io/${{ github.repository }}
            steps:
              - name: Checkout
                uses: actions/checkout@v7

              - name: Log in to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

              # Each build is pushed twice: :latest for convenience and an
              # immutable :sha-<commit> tag that deploy pins and rollback reuses.
              - name: Build and push image
                uses: docker/build-push-action@v6
                with:
                  context: .
                  push: true
                  tags: |
                    ${{ env.IMAGE }}:latest
                    ${{ env.IMAGE }}:sha-${{ github.sha }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

          deploy:
            needs: build
            runs-on: [self-hosted, pinqops-prod]
            permissions:
              contents: read
              packages: read
            env:
              APP_COMPOSE_PATH: ${{ vars.APP_COMPOSE_PATH || '/opt/pinqops/docker-compose.yml' }}
            steps:
              - name: Deploy with pinqops
                run: |
                  set -euo pipefail
                  echo "${{ secrets.GITHUB_TOKEN }}" \
                    | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                  pinqops deploy --compose-file "$APP_COMPOSE_PATH" --tag "sha-${{ github.sha }}"

              - name: Log out of GHCR
                if: always()
                run: docker logout ghcr.io || true
        """;

    /// <summary>The fixed compose project, pointed at the repo's GHCR image.</summary>
    public static string ComposeYaml(string owner, string repo) =>
        $$"""
        # Generated by pinqops-ui — the single, fixed application compose project.
        # `pinqops deploy` runs: docker compose pull && docker compose up -d
        name: pinqops

        services:
          app:
            # PINQOPS_TAG is pinned in this directory's .env by `pinqops deploy
            # --tag`, so the exact deployed version is recorded and can be
            # rolled back. Without a .env it falls back to :latest.
            image: ghcr.io/{{owner.ToLowerInvariant()}}/{{repo.ToLowerInvariant()}}:${PINQOPS_TAG:-latest}
            restart: unless-stopped
            # Add whatever YOUR application needs here (ports, networks, volumes, env):
            # ports:
            #   - "8080:8080"
        """;
}
