namespace PinqOps.Web;

/// <summary>
/// File templates the dashboard can materialize for a repository that is
/// missing them — the deploy workflow (committed to the repo via the GitHub
/// API) and the fixed server-side compose project.
/// </summary>
public static class SetupTemplates
{
    /// <summary>The workflow version the current template emits; bumped when the generated YAML gains features.</summary>
    public const int CurrentWorkflowVersion = 2;

    private const string WorkflowVersionMarker = "# pinqops-workflow-version:";

    /// <summary>
    /// The version stamped in a deploy workflow's <c>#&#160;pinqops-workflow-version: N</c>
    /// marker, or 1 when there is none (workflows generated before the marker
    /// existed). Lets the wizard offer an update when a repo is on an older shape.
    /// </summary>
    public static int ReadWorkflowVersion(string? workflowContent)
    {
        if (string.IsNullOrEmpty(workflowContent))
        {
            return 1;
        }

        foreach (var rawLine in workflowContent.Split('\n'))
        {
            var line = rawLine.Trim();
            if (line.StartsWith(WorkflowVersionMarker, StringComparison.Ordinal)
                && int.TryParse(line[WorkflowVersionMarker.Length..].Trim(), out var version)
                && version > 0)
            {
                return version;
            }
        }

        return 1;
    }

    /// <summary>Host port the compose project publishes on; editable in the dashboard's .env editor.</summary>
    public const string HostPortVariable = Deployer.HostPortVariable;

    /// <summary>Port inside the container the app listens on (seeded from the Dockerfile's EXPOSE).</summary>
    public const string ContainerPortVariable = Deployer.ContainerPortVariable;

    /// <summary>Mirror of examples/workflows/deploy.yml, ready to commit.</summary>
    /// <summary>
    /// The deploy workflow, triggered on <paramref name="defaultBranch"/>.
    /// </summary>
    /// <remarks>
    /// The branch must be the repository's real default branch: the dashboard
    /// commits this file there, and a trigger naming any other branch would
    /// simply never fire — GitHub does not warn about a filter that matches
    /// nothing, so the pipeline would look healthy and silently never deploy.
    /// </remarks>
    // Three '$' so the interpolation delimiter is {{{...}}}: the body is full of
    // GitHub Actions expressions like ${{ github.sha }}, and a two-'$' literal
    // would swallow those as C# interpolation holes.
    public static string DeployWorkflowYaml(string defaultBranch) =>
        $$$"""
        # pinqops-workflow-version: 2
        # Generated by pinqops-ui. Build in the cloud, deploy over the
        # self-hosted runner's outbound link — no inbound port on the server.
        # v2 adds per-PR preview environments (the preview-* jobs below).

        name: Build and Deploy

        on:
          push:
            branches:
              - {{{defaultBranch}}}
          # A pull request gets its own throwaway preview environment; closing it
          # tears the preview down. Only this repo's own PRs are built and
          # deployed (see the fork guard on the preview jobs).
          pull_request:
            types: [opened, synchronize, reopened, closed]
          # Lets the dashboard (or you, from the Actions tab) start a deploy
          # without pushing — the wizard uses this to kick off the first one.
          workflow_dispatch:

        permissions:
          contents: read

        jobs:
          build:
            # Production build: pushes and manual runs only. A PR uses preview-*.
            if: github.event_name != 'pull_request'
            runs-on: ubuntu-latest
            # A superseded build is pure waste, so cancel it. The deploy below is
            # deliberately NOT cancellable — see its own concurrency block.
            concurrency:
              group: build-${{ github.ref }}
              cancel-in-progress: true
            permissions:
              contents: read
              packages: write
            steps:
              - name: Checkout
                uses: actions/checkout@v7

              # GHCR repository names must be lowercase, but github.repository
              # keeps the repository's real case — resolve it once here.
              - name: Resolve image name
                id: image
                run: echo "name=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

              - name: Log in to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

              # Each build is pushed twice: :latest for convenience and an
              # immutable :sha-<commit> tag that deploy pins and rollback reuses.
              #
              # The image.source label is what connects the package to this
              # repository. Without it the link is left to implicit behaviour
              # that does NOT hold after a rename (a rename creates a new package
              # name), and the deploy job's GITHUB_TOKEN then gets 403 on pull.
              # Build context and Dockerfile default to the repository root; a
              # monorepo overrides them with the PINQOPS_BUILD_CONTEXT /
              # PINQOPS_DOCKERFILE repository variables (set by the dashboard when
              # you pick a subdirectory) — no workflow edit needed.
              - name: Build and push image
                uses: docker/build-push-action@v6
                with:
                  context: ${{ vars.PINQOPS_BUILD_CONTEXT || '.' }}
                  file: ${{ vars.PINQOPS_DOCKERFILE || format('{0}/Dockerfile', vars.PINQOPS_BUILD_CONTEXT || '.') }}
                  push: true
                  tags: |
                    ${{ steps.image.outputs.name }}:latest
                    ${{ steps.image.outputs.name }}:sha-${{ github.sha }}
                  labels: |
                    org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

          deploy:
            needs: build
            if: github.event_name != 'pull_request'
            runs-on: [self-hosted, pinqops-prod]
            # A deploy mutates the one fixed compose project on the server. Killing
            # it mid-flight can stop the app between `down` and `up` with no record
            # and no notification, so concurrent deploys queue instead.
            concurrency:
              group: deploy-${{ github.repository }}
              cancel-in-progress: false
            permissions:
              contents: read
              packages: read
            env:
              APP_COMPOSE_PATH: ${{ vars.APP_COMPOSE_PATH || '/opt/pinqops/docker-compose.yml' }}
            steps:
              - name: Deploy with pinqops
                run: |
                  set -euo pipefail
                  IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
                  echo "${{ secrets.GITHUB_TOKEN }}" \
                    | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                  pinqops deploy --compose-file "$APP_COMPOSE_PATH" --tag "sha-${{ github.sha }}" \
                    --image "$IMAGE"

              - name: Log out of GHCR
                if: always()
                run: docker logout ghcr.io || true

          # ---- Preview environments (one per pull request) ----

          # Build a PR's image in the cloud. The fork guard is a HARD SECURITY
          # boundary: a fork's PR must never build code that then runs the
          # preview-deploy job on your self-hosted server. Skipped on 'closed'.
          preview-build:
            if: >-
              github.event_name == 'pull_request'
              && github.event.action != 'closed'
              && github.event.pull_request.head.repo.full_name == github.repository
            runs-on: ubuntu-latest
            concurrency:
              group: preview-build-${{ github.repository }}-${{ github.event.pull_request.number }}
              cancel-in-progress: true
            permissions:
              contents: read
              packages: write
            steps:
              - name: Checkout
                uses: actions/checkout@v7

              - name: Resolve image name
                id: image
                run: echo "name=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

              - name: Log in to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

              # Only the immutable :sha-<commit> tag — a preview build must never
              # move :latest, which production tracks by default.
              - name: Build and push preview image
                uses: docker/build-push-action@v6
                with:
                  context: ${{ vars.PINQOPS_BUILD_CONTEXT || '.' }}
                  file: ${{ vars.PINQOPS_DOCKERFILE || format('{0}/Dockerfile', vars.PINQOPS_BUILD_CONTEXT || '.') }}
                  push: true
                  tags: ${{ steps.image.outputs.name }}:sha-${{ github.sha }}
                  labels: |
                    org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

          preview-deploy:
            needs: preview-build
            runs-on: [self-hosted, pinqops-prod]
            # Serialise deploy and teardown for the same PR so a fast close after a
            # push can't race — same group, never cancelled.
            concurrency:
              group: preview-${{ github.repository }}-${{ github.event.pull_request.number }}
              cancel-in-progress: false
            permissions:
              contents: read
              packages: read
            env:
              APP_COMPOSE_PATH: ${{ vars.APP_COMPOSE_PATH || '/opt/pinqops/docker-compose.yml' }}
            steps:
              - name: Deploy preview with pinqops
                run: |
                  set -euo pipefail
                  IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
                  echo "${{ secrets.GITHUB_TOKEN }}" \
                    | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                  pinqops preview deploy --compose-file "$APP_COMPOSE_PATH" \
                    --pr "${{ github.event.pull_request.number }}" \
                    --image "$IMAGE" --tag "sha-${{ github.sha }}"

              - name: Log out of GHCR
                if: always()
                run: docker logout ghcr.io || true

          # Tear the preview down when the PR closes (merged or not). No build and
          # no registry access needed — just remove the project and its route.
          preview-teardown:
            if: >-
              github.event_name == 'pull_request'
              && github.event.action == 'closed'
              && github.event.pull_request.head.repo.full_name == github.repository
            runs-on: [self-hosted, pinqops-prod]
            concurrency:
              group: preview-${{ github.repository }}-${{ github.event.pull_request.number }}
              cancel-in-progress: false
            permissions:
              contents: read
            env:
              APP_COMPOSE_PATH: ${{ vars.APP_COMPOSE_PATH || '/opt/pinqops/docker-compose.yml' }}
            steps:
              - name: Tear down preview with pinqops
                run: |
                  set -euo pipefail
                  pinqops preview teardown --compose-file "$APP_COMPOSE_PATH" \
                    --pr "${{ github.event.pull_request.number }}" \
                    --owner "${GITHUB_REPOSITORY%%/*}" --repo "${GITHUB_REPOSITORY##*/}"
        """;

    /// <summary>
    /// The fixed compose project, pointed at the repo's GHCR image. The project
    /// is named after the repository, so containers read
    /// <c>&lt;repo&gt;-app-1</c>. <paramref name="containerPort"/> is the port the
    /// image listens on (read from the repo's Dockerfile EXPOSE) and only sets
    /// the default — both ports are overridable from the dashboard's .env editor.
    /// </summary>
    public static string ComposeYaml(string owner, string repo, int hostPort, int containerPort) =>
        ComposeTemplate.Yaml(owner, repo, ComposeProjectName.FromRepository(repo), hostPort, containerPort);
}
