namespace PinqOps.Web;

/// <summary>
/// File templates the dashboard can materialize for a repository that is
/// missing them — the deploy workflow (committed to the repo via the GitHub
/// API) and the fixed server-side compose project.
/// </summary>
public static class SetupTemplates
{
    /// <summary>Host port the compose project publishes on; editable in the dashboard's .env editor.</summary>
    public const string HostPortVariable = "PINQOPS_HOST_PORT";

    /// <summary>Port inside the container the app listens on (seeded from the Dockerfile's EXPOSE).</summary>
    public const string ContainerPortVariable = "PINQOPS_CONTAINER_PORT";

    /// <summary>Mirror of examples/workflows/deploy.yml, ready to commit.</summary>
    public const string DeployWorkflowYaml =
        """
        # Generated by pinqops-ui. Build in the cloud, deploy over the
        # self-hosted runner's outbound link — no inbound port on the server.

        name: Build and Deploy

        on:
          push:
            branches:
              - master

        permissions:
          contents: read

        jobs:
          build:
            runs-on: ubuntu-latest
            # A superseded build is pure waste, so cancel it. The deploy below is
            # deliberately NOT cancellable — see its own concurrency block.
            concurrency:
              group: build-${{ github.ref }}
              cancel-in-progress: true
            permissions:
              contents: read
              packages: write
            steps:
              - name: Checkout
                uses: actions/checkout@v7

              # GHCR repository names must be lowercase, but github.repository
              # keeps the repository's real case — resolve it once here.
              - name: Resolve image name
                id: image
                run: echo "name=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

              - name: Log in to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

              # Each build is pushed twice: :latest for convenience and an
              # immutable :sha-<commit> tag that deploy pins and rollback reuses.
              #
              # The image.source label is what connects the package to this
              # repository. Without it the link is left to implicit behaviour
              # that does NOT hold after a rename (a rename creates a new package
              # name), and the deploy job's GITHUB_TOKEN then gets 403 on pull.
              - name: Build and push image
                uses: docker/build-push-action@v6
                with:
                  context: .
                  push: true
                  tags: |
                    ${{ steps.image.outputs.name }}:latest
                    ${{ steps.image.outputs.name }}:sha-${{ github.sha }}
                  labels: |
                    org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

          deploy:
            needs: build
            runs-on: [self-hosted, pinqops-prod]
            # A deploy mutates the one fixed compose project on the server. Killing
            # it mid-flight can stop the app between `down` and `up` with no record
            # and no notification, so concurrent deploys queue instead.
            concurrency:
              group: deploy-${{ github.repository }}
              cancel-in-progress: false
            permissions:
              contents: read
              packages: read
            env:
              APP_COMPOSE_PATH: ${{ vars.APP_COMPOSE_PATH || '/opt/pinqops/docker-compose.yml' }}
            steps:
              - name: Deploy with pinqops
                run: |
                  set -euo pipefail
                  IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
                  echo "${{ secrets.GITHUB_TOKEN }}" \
                    | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                  pinqops deploy --compose-file "$APP_COMPOSE_PATH" --tag "sha-${{ github.sha }}" \
                    --image "$IMAGE"

              - name: Log out of GHCR
                if: always()
                run: docker logout ghcr.io || true
        """;

    /// <summary>
    /// The fixed compose project, pointed at the repo's GHCR image. The project
    /// is named after the repository, so containers read
    /// <c>&lt;repo&gt;-app-1</c>. <paramref name="containerPort"/> is the port the
    /// image listens on (read from the repo's Dockerfile EXPOSE) and only sets
    /// the default — both ports are overridable from the dashboard's .env editor.
    /// </summary>
    public static string ComposeYaml(string owner, string repo, int hostPort, int containerPort) =>
        $$"""
        # Generated by pinqops-ui — the single, fixed application compose project.
        # `pinqops deploy` runs: docker compose pull && docker compose up -d
        # Quoted: an all-digit repository name (e.g. "2048") would otherwise be
        # read as a YAML integer and compose rejects the file outright.
        name: "{{ComposeProjectName.FromRepository(repo)}}"

        services:
          app:
            # Both variables are pinned in this directory's .env by `pinqops
            # deploy` (PINQOPS_IMAGE from --image, PINQOPS_TAG from --tag), so the
            # image always follows the repository — even after a rename — and the
            # exact version is recorded and can be rolled back. The defaults below
            # are used only before the first deploy (or a plain `docker compose up`).
            image: ${PINQOPS_IMAGE:-ghcr.io/{{owner.ToLowerInvariant()}}/{{repo.ToLowerInvariant()}}}:${PINQOPS_TAG:-latest}
            restart: unless-stopped
            # <host>:<container>. Change the host port from the dashboard's .env
            # editor (PINQOPS_HOST_PORT) and press Apply — no need to edit YAML.
            # PINQOPS_CONTAINER_PORT is the port your image listens on; it was
            # read from your Dockerfile's EXPOSE.
            ports:
              - "${PINQOPS_HOST_PORT:-{{hostPort}}}:${PINQOPS_CONTAINER_PORT:-{{containerPort}}}"
            # pinqops-apps is the shared network the catalog apps live on — it
            # lets this app reach them (Redis, PostgreSQL, …) by container DNS.
            networks: [default, pinqops-apps]
            # Add whatever else YOUR application needs here (volumes, env):

        networks:
          pinqops-apps:
            external: true
        """;
}
