using System.Text;

namespace PinqOps.Proxy;

/// <summary>
/// Renders a Caddyfile from a <see cref="DomainConfig"/>. Pure and
/// deterministic (LF line endings) so it can be snapshot-tested and produced
/// identically by the dashboard and the runner CLI. Caddy handles Let's Encrypt
/// automatically; the only global settings are the ACME e-mail and an optional
/// staging CA for testing.
/// </summary>
public static class CaddyfileGenerator
{
    public static string Generate(DomainConfig config)
    {
        ArgumentNullException.ThrowIfNull(config);

        var builder = new StringBuilder();
        builder.Append("# Generated by pinqops-ui — do not edit; changes are overwritten.\n");

        var global = new List<string>();
        if (!string.IsNullOrWhiteSpace(config.AcmeEmail))
        {
            global.Add($"email {config.AcmeEmail.Trim()}");
        }

        if (config.UseStagingCa)
        {
            global.Add("acme_ca https://acme-staging-v02.api.letsencrypt.org/directory");
        }

        if (global.Count > 0)
        {
            builder.Append("{\n");
            foreach (var line in global)
            {
                builder.Append("    ").Append(line).Append('\n');
            }

            builder.Append("}\n");
        }

        foreach (var entry in config.Domains)
        {
            if (!entry.Enabled || string.IsNullOrWhiteSpace(entry.TargetContainer) || entry.TargetPort <= 0)
            {
                continue;
            }

            builder.Append('\n')
                .Append(entry.Domain).Append(" {\n")
                .Append("    reverse_proxy ").Append(entry.TargetContainer).Append(':').Append(entry.TargetPort).Append('\n')
                .Append("}\n");
        }

        return builder.ToString();
    }
}
