using System.Text;

namespace PinqOps.Proxy;

/// <summary>
/// Renders a Caddyfile from a <see cref="DomainConfig"/>. Pure and
/// deterministic (LF line endings) so it can be snapshot-tested and produced
/// identically by the dashboard and the runner CLI. Caddy handles Let's Encrypt
/// automatically; the only global settings are the ACME e-mail and an optional
/// staging CA for testing.
/// </summary>
public static class CaddyfileGenerator
{
    public static string Generate(DomainConfig config)
    {
        ArgumentNullException.ThrowIfNull(config);

        var builder = new StringBuilder();
        builder.Append("# Generated by pinqops-ui — do not edit; changes are overwritten.\n");

        var global = new List<string>();
        if (!string.IsNullOrWhiteSpace(config.AcmeEmail) && IsSafeGlobalValue(config.AcmeEmail))
        {
            global.Add($"email {config.AcmeEmail.Trim()}");
        }

        if (config.UseStagingCa)
        {
            global.Add("acme_ca https://acme-staging-v02.api.letsencrypt.org/directory");
        }

        if (global.Count > 0)
        {
            builder.Append("{\n");
            foreach (var line in global)
            {
                builder.Append("    ").Append(line).Append('\n');
            }

            builder.Append("}\n");
        }

        foreach (var entry in config.Domains)
        {
            if (!entry.Enabled || string.IsNullOrWhiteSpace(entry.TargetContainer) || entry.TargetPort <= 0)
            {
                continue;
            }

            // domains.json is written by both the dashboard and the runner CLI
            // and loaded without validation, so this generator is the last
            // boundary before Caddy executes the file. Re-validate here: a
            // hand-edited or corrupt entry whose domain or container name carries
            // whitespace, braces or newlines would otherwise inject arbitrary
            // Caddy directives (an extra site block, a second upstream). Skip
            // anything that does not pass rather than emit it.
            string domain;
            try
            {
                domain = DomainName.Normalize(entry.Domain);
            }
            catch (ArgumentException)
            {
                continue;
            }

            if (!IsValidContainerName(entry.TargetContainer))
            {
                continue;
            }

            builder.Append('\n')
                .Append(domain).Append(" {\n")
                .Append("    reverse_proxy ").Append(entry.TargetContainer).Append(':').Append(entry.TargetPort).Append('\n')
                .Append("}\n");
        }

        return builder.ToString();
    }

    /// <summary>A docker container/service name: starts alphanumeric, then only
    /// <c>[a-zA-Z0-9_.-]</c>. Rejects whitespace and anything that could break out
    /// of the <c>reverse_proxy</c> line into a second upstream or directive.</summary>
    private static bool IsValidContainerName(string name) =>
        name.Length > 0
        && char.IsAsciiLetterOrDigit(name[0])
        && name.All(c => char.IsAsciiLetterOrDigit(c) || c is '_' or '.' or '-');

    /// <summary>Guards a value emitted into the global block (the ACME e-mail):
    /// no whitespace, braces or control characters that could open or close a
    /// block.</summary>
    private static bool IsSafeGlobalValue(string value)
    {
        var trimmed = value.Trim();
        return trimmed.Length > 0
            && trimmed.All(c => !char.IsWhiteSpace(c) && !char.IsControl(c) && c is not ('{' or '}'));
    }
}
